plugin: azure.azcollection.azure_rm
auth_source: cli            
include_vm_resource_groups:
  - rg-k8s-skander          

keyed_groups:
  - key: tags.kubernetes_role
    prefix: role
    separator: "_"
vars:
  ansible_python_interpreter: /usr/bin/python3
hostvar_expressions:
  ansible_host: public_ipv4_addresses | first